language: python
serices:
   - docker
install:
   - make deps
script:
   - make lint
   - make test
   - make docker_build
   - make docker_push
deploy:
   provider: heroku
   app: stormy-atoll-41045
   api_key: ${HEROKU_API_KEY}
